### ISSUE TITLE
Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by VijayaSaiRam** [wojtekmaj/react-pdf#1818]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

 I have upgraded to react-pdf: 9.0.0 .and for polyfills, I have used as follows

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
 'pdfjs-dist/legacy/build/pdf.worker.min.mjs',
 import.meta.url,
).toString();
but test cases are failing by giving this error. 
    SyntaxError: Cannot use 'import.meta' outside a module
Could you please let me know how to fix this issue.

### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-

### Additional information

-

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
The code looks alright, provided that the configuration of your tooling is alright. I have no information regarding your tools and their configuration so I cannot help you.

**Comment by VijayaSaiRam** [comment]
Hi , I am Using React 18
node version 20.12.2
and yarn
react-pdf-9.0.0

**Comment by Odiga** [comment]
same here

**Comment by pironev** [comment]
Try to use somthing like this
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

**Comment by VijayaSaiRam** [comment]
I cannot use like that as I don't have the access to it from app

**Comment by wojtekmaj** [comment]
Unfortunately, Jest has really, really poor (and still experimental - for years) support for ESM and my official recommendation to work around this issue is going to be: **migrate to Vitest**. As soon as you manage to go around the `import.meta` issue, the next issue is going to hit you (#1810). Do yourself a favor, save yourself from the headaches.

**Comment by EmilySaber** [comment]
Are there any plans to fix this? Aside from the suggestion to migrate to Vitest
The only solution I could find was to bring in the` babel-plugin-transform-import-meta` plugin into the jest config but you are correct in this being a true headache

**Comment by wojtekmaj** [comment]
There are no plans to fix this, because nothing is broken. As per my last comment - Jest simply isn't suited for use with modern day applications. Nevertheless, if you find good workarounds for Jest, feel free to share them.

**Comment by lajanzen** [comment]
For me this issue was fixed with Implementation of [babel-plugin-transform-import-meta](https://github.com/javiertury/babel-plugin-transform-import-meta) as described here: https://stackoverflow.com/questions/64961387/how-to-use-import-meta-when-testing-with-jest

We have a huge project with hundreds of unit tests so switching from Jest to Vitest was not an option.

**Comment by ryanmlow** [comment]
For me I solved it in 2 steps:
1. Refactor `import.meta.url` into its own function in a separate file like `getMetaUrl.ts`
`export const getMetaUrl = () => new URL(‘pdfjs-dist/build/pdf.worker.min.js’, import.meta.url)`

2. Mock this function in the root level of your test file `mytest.test.ts`. Include the line:
`jest.mock(‘/path/to/getMetaUrl.ts’, ()=> ({
  getMetaUrl: jest.fn()
}))`

In your PDF viewer component, just retrieve URL using the function 
`pdfjs.GlobalWorkerOptions.workerSrc = getMetaUrl()`
