### ISSUE TITLE
Officially release 4.0.0

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-pdf#269]
It looks like the code is well tested and we're ready to go. Here's what needs to be done/resolved before we continue:

* [x] Babel 7 failing in linked packages - babel/babel#8667
* [x] Merge Upgrade to Babel 7.0.0 - #270
* [x] Official, stable release of PDF.js - mozilla/pdf.js#9521
* [x] Release of PDF.js 2.0.943 on npm - mozilla/pdf.js#10181
* [x] Upgrade to PDF.js stable 2.x version
    * [x] Resolve issue with `pdfInfo` now being a private field
    * [x] Resolve issue with "garbage" text used to render texts in SVG and breaking our TextLayer - mozilla/pdf.js#10205 1020
* [x] Write Release Notes
* [x] Write Upgrade Guide

Once these are done, we can go on and release final version of React-PDF 4.0.0 🎉

**Comment by haf** [comment]
Testing `v4-beta.4` w/ Babel 7 w/ Mocha and this import:

```js
import { Document, Page } from 'react-pdf/dist/entry.webpack';
```

Crashes like so:

```
Error: Cannot find module 'worker-loader!./pdf.worker.entry.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/node_modules/react-pdf/dist/entry.webpack.js:24:23)
    at Module._compile (module.js:652:30)
    at Module._compile (/root/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/root/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/app/expenses/components/Documents/PDFDocument.js:4:1)
```

The workaround with `dist/no.worker` doesn't work anymore, because that file doesn't exist in `beta.4` and I haven't got [worker-loader](https://github.com/webpack-contrib/worker-loader/) installed; is it required from now on? I can compile and run the app normally without installing it; only mocha has issues.

**Comment by wojtekmaj** [comment]
No, worker-loader was always `pdfjs-dist`'s dependency and continues to be so. Would you kindly raise an issue for that, with more details on your environment config (used Webpack version etc.)?

**Comment by timvandermeij** [comment]
Hi, I just wanted to let you know that yesterday we managed to publish PDF.js 2.0.943 on NPM too, see https://www.npmjs.com/package/pdfjs-dist, since I think you were waiting for it. As always, please feel free to let us know if there are any issues. Hopefully the upgrade works out well!

**Comment by wojtekmaj** [comment]
Thank you @timvandermeij for the heads up! :)

**Comment by wojtekmaj** [comment]
Tadaaa! Enjoy stable 4.0.0, everyone! :)

**Comment by haf** [comment]
Yey!
